name = "recipe-scraper"
main = "worker-recipe-scraper.js"
compatibility_date = "2024-09-30"

# Workers free tier: 100,000 requests/day
# https://workers.cloudflare.com

[env.production]
name = "recipe-scraper-prod"
